spring:
  data:
    mongodb:
      password: alibou
      username: alibou
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ecom.ecommerce.order.kafka.OrderConfirmation,paymentConfirmation:com.ecom.ecommerce.payment.request.PaymentNotificationRequest
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: manoj
    password: manoj
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040